name: keystore

on:
    # Manual triggers
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
      dry-run:
        description: Creates a draft release
        required: false

jobs:
  buildRelease:
    name: Build Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        with:
          repository: 'nanihadesuka/NovelDokusha'
          fetch-depth: 0
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          repository: 'nanihadesuka/NovelDokusha'
          fetch-depth: 0
          ref: ${{ github.event.inputs.git-ref }}

      - name: Set up JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      - name: Setup Python enviroment
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Setup Gradle version to 8.1.1
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1

      - name: Get previous release
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"
          view_top: 1

      - name: Prepare build
        run: |
          set -e

          commit_count=$(git rev-list --count HEAD)
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_ENV
          current_sha=$(git rev-parse --short HEAD)
          echo "CURRENT_SHA=$current_sha" >> $GITHUB_ENV

          prev_commit_count=$(echo "${{ steps.last_release.outputs.tag_name }}" | sed -e "s/^r//")
          commit_count_diff=$(expr $commit_count - $prev_commit_count)
          prev_release_sha=$(git rev-parse --short HEAD~$commit_count_diff)
          echo "PREV_RELEASE_SHA=$prev_release_sha" >> $GITHUB_ENV

          echo "COMMIT_LOGS<<{delimiter}
          $(curl -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/nanihadesuka/NovelDokusha/compare/$prev_release_sha...$current_sha" \
            | jq '[.commits[]|{message:(.commit.message | split("\n")), username:.author.login}]' \
            | jq -r '.[]|"- \(.message | first) (@\(.username))"')
          {delimiter}" >> $GITHUB_ENV

      - name: Setup APK signing
        run: |
          echo -n ${{ secrets.SIGNING_KEY }} | base64 -d > app/storeFile.jsk
          echo storeFile=storeFile.jsk > custom.properties
          echo storePassword=${{ secrets.KEY_STORE_PASSWORD }} >> custom.properties
          echo keyAlias=${{ secrets.ALIAS }} >> custom.properties
          echo keyPassword=${{ secrets.KEY_PASSWORD }} >> custom.properties

      - name: Create Release
        uses: actions/upload-artifact@v2
        with:
            name: keystore
            path:  ./**/*.jsk

            
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
             name: keystore
