name: Publish Release

on:
    # Manual triggers
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
      dry-run:
        description: Creates a draft release
        required: false

jobs:
  buildRelease:
    name: Build Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        with:
          repository: 'nanihadesuka/NovelDokusha'
          fetch-depth: 0
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          repository: 'nanihadesuka/NovelDokusha'
          fetch-depth: 0
          ref: ${{ github.event.inputs.git-ref }}

      - name: Set up JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      - name: Setup Python enviroment
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Setup Gradle version to 8.2.1
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2.1

      - name: Get previous release
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"
          view_top: 1

      - name: Prepare build
        run: |
          set -e

          commit_count=$(git rev-list --count HEAD)
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_ENV
          current_sha=$(git rev-parse --short HEAD)
          echo "CURRENT_SHA=$current_sha" >> $GITHUB_ENV

          prev_commit_count=$(echo "${{ steps.last_release.outputs.tag_name }}" | sed -e "s/^r//")
          commit_count_diff=$(expr $commit_count - $prev_commit_count)
          prev_release_sha=$(git rev-parse --short HEAD~$commit_count_diff)
          echo "PREV_RELEASE_SHA=$prev_release_sha" >> $GITHUB_ENV

          echo "COMMIT_LOGS<<{delimiter}
          $(curl -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/nanihadesuka/NovelDokusha/compare/$prev_release_sha...$current_sha" \
            | jq '[.commits[]|{message:(.commit.message | split("\n")), username:.author.login}]' \
            | jq -r '.[]|"- \(.message | first) (@\(.username))"')
          {delimiter}" >> $GITHUB_ENV

      - name: Setup APK signing
        run: |
          echo -n ${{ secrets.SIGNING_KEY }} | base64 -d > app/storeFile.jsk
          echo storeFile=storeFile.jsk > custom.properties
          echo storePassword=${{ secrets.KEY_STORE_PASSWORD }} >> custom.properties
          echo keyAlias=${{ secrets.ALIAS }} >> custom.properties
          echo keyPassword=${{ secrets.KEY_PASSWORD }} >> custom.properties

      - name: Build app
        run: |
          gradle assembleFullRelease -PsplitByAbi -PsplitByAbiDoUniversal -PlocalPropertiesFilePath=custom.properties


      - name: Clean up build artifacts
        run: |
          set -e

          cp app/build/outputs/apk/full/release/*-full-universal-release.apk NovelDokusha-full-universal-r${{ env.COMMIT_COUNT }}.apk
          sha=`sha256sum NovelDokusha-full-universal-r${{ env.COMMIT_COUNT }}.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/full/release/*-full-arm64-v8a-release.apk NovelDokusha-full-arm64-v8a-r${{ env.COMMIT_COUNT }}.apk
          sha=`sha256sum NovelDokusha-full-arm64-v8a-r${{ env.COMMIT_COUNT }}.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/full/release/*-full-armeabi-v7a-release.apk NovelDokusha-full-armeabi-v7a-r${{ env.COMMIT_COUNT }}.apk
          sha=`sha256sum NovelDokusha-full-armeabi-v7a-r${{ env.COMMIT_COUNT }}.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/full/release/*-full-x86-release.apk NovelDokusha-full-x86-r${{ env.COMMIT_COUNT }}.apk
          sha=`sha256sum NovelDokusha-full-x86-r${{ env.COMMIT_COUNT }}.apk | awk '{ print $1 }'`
          echo "APK_X86_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/full/release/*-full-x86_64-release.apk NovelDokusha-full-x86_64-r${{ env.COMMIT_COUNT }}.apk
          sha=`sha256sum NovelDokusha-full-x86_64-r${{ env.COMMIT_COUNT }}.apk | awk '{ print $1 }'`
          echo "APK_X86_64_SHA=$sha" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: r${{ env.COMMIT_COUNT }}
          name: NovelDokusha full r${{ env.COMMIT_COUNT }}
          body: |
            ### Commits

            https://github.com/nanihadesuka/NovelDokusha/compare/${{ env.PREV_RELEASE_SHA }}...${{ env.CURRENT_SHA }}

            ${{ env.COMMIT_LOGS }}

            ---

            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | Universal | ${{ env.APK_UNIVERSAL_SHA }}
            | arm64-v8a | ${{ env.APK_ARM64_V8A_SHA }}
            | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }}
            | x86 | ${{ env.APK_X86_SHA }}
            | x86_64 | ${{ ENV.APK_X86_64_SHA }} |
          files: |
            NovelDokusha-full-universal-r${{ env.COMMIT_COUNT }}.apk
            NovelDokusha-full-arm64-v8a-r${{ env.COMMIT_COUNT }}.apk
            NovelDokusha-full-armeabi-v7a-r${{ env.COMMIT_COUNT }}.apk
            NovelDokusha-full-x86-r${{ env.COMMIT_COUNT }}.apk
            NovelDokusha-full-x86_64-r${{ env.COMMIT_COUNT }}.apk
          draft: ${{ github.event.inputs.dry-run != '' }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
